// Original classic theme definitions retain their upstream attribution; see ATTRIBUTION.txt.
(() => {
  "use strict";
  const builtins = [
    {
      name: "Jade Orchard",
      id: "theme1",
      group: "Classics",
      colors: ["#56b69f", "#9eca67", "#9eca67"],
      accent: "#56b69f",
      angle: 180,
      kind: "linear",
    },
    {
      name: "Amber Horizon",
      id: "theme2",
      group: "Classics",
      colors: ["#f3b336", "#ee8558", "#ee8558"],
      accent: "#f3b336",
      angle: 180,
      kind: "linear",
    },
    {
      name: "Rosewater",
      id: "theme3",
      group: "Classics",
      colors: ["#3a7ca1", "#3a7ca1", "#3a7ca1"],
      accent: "#3a7ca1",
      angle: 149,
      kind: "linear",
    },
    {
      name: "Lavender Veil",
      id: "theme4",
      group: "Classics",
      colors: ["#efaab3", "#a6daa2", "#a6daa2"],
      accent: "#efaab3",
      angle: 38,
      kind: "linear",
    },
    {
      name: "Coral Bloom",
      id: "theme5",
      group: "Classics",
      colors: ["#9f4175", "#a6953d", "#a6953d"],
      accent: "#9f4175",
      angle: 154,
      kind: "linear",
    },
    {
      name: "Citrus Sunrise",
      id: "theme6",
      group: "Classics",
      colors: ["#f4abb8", "#b1c2fc", "#b1c2fc"],
      accent: "#f4abb8",
      angle: 180,
      kind: "linear",
    },
    {
      name: "Desert Mirage",
      id: "theme7",
      group: "Classics",
      colors: ["#a4c0f7", "#cfdfa2", "#cfdfa2"],
      accent: "#a4c0f7",
      angle: 180,
      kind: "linear",
    },
    {
      name: "Emberwood",
      id: "theme8",
      group: "Classics",
      colors: ["#e7dbd0", "#e0d6a3", "#e0d6a3"],
      accent: "#e7dbd0",
      angle: 39,
      kind: "linear",
    },
    {
      name: "Glacier Mist",
      id: "theme9",
      group: "Classics",
      colors: ["#48288c", "#db7f4b", "#db7f4b"],
      accent: "#48288c",
      angle: 142,
      kind: "linear",
    },
    {
      name: "Silver Haze",
      id: "theme10",
      group: "Classics",
      colors: ["#0eb5bf", "#218be0", "#218be0"],
      accent: "#0eb5bf",
      angle: 129,
      kind: "linear",
    },
    {
      name: "Onyx Night",
      id: "theme11",
      group: "Classics",
      colors: ["#142215", "#a98e4b", "#a98e4b"],
      accent: "#142215",
      angle: 162,
      kind: "linear",
    },
    {
      name: "Forest Canopy",
      id: "theme12",
      group: "Classics",
      colors: ["#950909", "#000000", "#000000"],
      accent: "#950909",
      angle: 65,
      kind: "linear",
    },
    {
      name: "Violet Eclipse",
      id: "theme13",
      group: "Classics",
      colors: ["#5348ca", "#140730", "#140730"],
      accent: "#5348ca",
      angle: 48,
      kind: "linear",
    },
    {
      name: "Copper Canyon",
      id: "theme14",
      group: "Classics",
      colors: ["#895240", "#8f4343", "#8f4343"],
      accent: "#895240",
      angle: 171,
      kind: "linear",
    },
    {
      name: "Evening Reverie",
      id: "theme15",
      group: "Classics",
      colors: ["#665069", "#91a3d1", "#91a3d1"],
      accent: "#665069",
      angle: 180,
      kind: "linear",
    },
    {
      name: "Tidal Garden",
      id: "theme16",
      group: "Classics",
      colors: ["#647962", "#6a8482", "#6a8482"],
      accent: "#647962",
      angle: 179,
      kind: "linear",
    },
    {
      name: "Electric Rain",
      id: "theme17",
      group: "Classics",
      colors: ["#3a7ca1", "#3a7ca1", "#3a7ca1"],
      accent: "#3a7ca1",
      angle: 149,
      kind: "linear",
    },
    {
      name: "Afterhours",
      id: "theme18",
      group: "Classics",
      colors: ["#01a89e", "#b43898", "#b43898"],
      accent: "#01a89e",
      angle: 180,
      kind: "linear",
    },
    {
      name: "Berry Sorbet",
      id: "theme19",
      group: "Classics",
      colors: ["#af1a6c", "#e7a525", "#e7a525"],
      accent: "#af1a6c",
      angle: 161,
      kind: "linear",
    },
    {
      name: "Polar Lights",
      id: "theme20",
      group: "Classics",
      colors: ["#062053", "#051a81", "#051a81"],
      accent: "#062053",
      angle: 239,
      kind: "linear",
    },
    {
      name: "Indigo Hour",
      id: "theme21",
      group: "Classics",
      colors: ["#2c3fe7", "#261d83", "#261d83"],
      accent: "#2c3fe7",
      angle: 48,
      kind: "linear",
    },
    {
      id: "lumgram-01",
      name: "Moonstone",
      group: "LumGram 50",
      colors: ["#34363c", "#96989e", "#deded9"],
      accent: "#deded9",
      angle: 135,
      kind: "radial",
    },
    {
      id: "lumgram-02",
      name: "Frosted Quartz",
      group: "LumGram 50",
      colors: ["#625d67", "#b5adb7", "#e6dddd"],
      accent: "#e6dddd",
      angle: 160,
      kind: "linear",
    },
    {
      id: "lumgram-03",
      name: "Carbon Silk",
      group: "LumGram 50",
      colors: ["#08090b", "#25262b", "#62656b"],
      accent: "#62656b",
      angle: 45,
      kind: "linear",
    },
    {
      id: "lumgram-04",
      name: "Pearl Drift",
      group: "LumGram 50",
      colors: ["#656f75", "#c8c9c7", "#efebe4"],
      accent: "#efebe4",
      angle: 180,
      kind: "linear",
    },
    {
      id: "lumgram-05",
      name: "Smoke & Mirrors",
      group: "LumGram 50",
      colors: ["#26262a", "#777176", "#b9b2ae"],
      accent: "#b9b2ae",
      angle: 110,
      kind: "linear",
    },
    {
      id: "lumgram-06",
      name: "Arctic Dawn",
      group: "LumGram 50",
      colors: ["#143c50", "#78abb7", "#e5d8ba"],
      accent: "#e5d8ba",
      angle: 135,
      kind: "linear",
    },
    {
      id: "lumgram-07",
      name: "Boreal Lake",
      group: "LumGram 50",
      colors: ["#062c36", "#24756c", "#9ca884"],
      accent: "#9ca884",
      angle: 160,
      kind: "linear",
    },
    {
      id: "lumgram-08",
      name: "Deep Current",
      group: "LumGram 50",
      colors: ["#071821", "#123c59", "#197d8b"],
      accent: "#197d8b",
      angle: 45,
      kind: "radial",
    },
    {
      id: "lumgram-09",
      name: "Lagoon Glass",
      group: "LumGram 50",
      colors: ["#173e45", "#38948e", "#a0d6c0"],
      accent: "#a0d6c0",
      angle: 180,
      kind: "linear",
    },
    {
      id: "lumgram-10",
      name: "Seafoam Atelier",
      group: "LumGram 50",
      colors: ["#315b55", "#8ba995", "#d0d2b4"],
      accent: "#d0d2b4",
      angle: 110,
      kind: "linear",
    },
    {
      id: "lumgram-11",
      name: "Moss Cathedral",
      group: "LumGram 50",
      colors: ["#16261f", "#3c6046", "#939469"],
      accent: "#939469",
      angle: 135,
      kind: "linear",
    },
    {
      id: "lumgram-12",
      name: "Fernlight",
      group: "LumGram 50",
      colors: ["#1f4233", "#62865a", "#c3c08c"],
      accent: "#c3c08c",
      angle: 160,
      kind: "linear",
    },
    {
      id: "lumgram-13",
      name: "Olive Grove",
      group: "LumGram 50",
      colors: ["#343b23", "#858755", "#d6bd87"],
      accent: "#d6bd87",
      angle: 45,
      kind: "linear",
    },
    {
      id: "lumgram-14",
      name: "Juniper Trail",
      group: "LumGram 50",
      colors: ["#102e2f", "#376768", "#9cad9c"],
      accent: "#9cad9c",
      angle: 180,
      kind: "linear",
    },
    {
      id: "lumgram-15",
      name: "Emerald Hour",
      group: "LumGram 50",
      colors: ["#072622", "#12664d", "#78b591"],
      accent: "#78b591",
      angle: 110,
      kind: "radial",
    },
    {
      id: "lumgram-16",
      name: "Golden Hour",
      group: "LumGram 50",
      colors: ["#493021", "#b37b47", "#ecd0a0"],
      accent: "#ecd0a0",
      angle: 135,
      kind: "linear",
    },
    {
      id: "lumgram-17",
      name: "Desert Linen",
      group: "LumGram 50",
      colors: ["#514335", "#9d8870", "#ddd0b6"],
      accent: "#ddd0b6",
      angle: 160,
      kind: "linear",
    },
    {
      id: "lumgram-18",
      name: "Saffron Sky",
      group: "LumGram 50",
      colors: ["#74352a", "#d98d42", "#ecd187"],
      accent: "#ecd187",
      angle: 45,
      kind: "linear",
    },
    {
      id: "lumgram-19",
      name: "Honey Glass",
      group: "LumGram 50",
      colors: ["#35261d", "#9e6a30", "#d8b975"],
      accent: "#d8b975",
      angle: 180,
      kind: "linear",
    },
    {
      id: "lumgram-20",
      name: "Champagne Mist",
      group: "LumGram 50",
      colors: ["#5e524b", "#ab998d", "#ded3c2"],
      accent: "#ded3c2",
      angle: 110,
      kind: "linear",
    },
    {
      id: "lumgram-21",
      name: "Burnt Sienna",
      group: "LumGram 50",
      colors: ["#362328", "#9b453a", "#d29165"],
      accent: "#d29165",
      angle: 135,
      kind: "linear",
    },
    {
      id: "lumgram-22",
      name: "Terracotta Moon",
      group: "LumGram 50",
      colors: ["#4b2b2c", "#ab7060", "#dac0a2"],
      accent: "#dac0a2",
      angle: 160,
      kind: "radial",
    },
    {
      id: "lumgram-23",
      name: "Coral Reef",
      group: "LumGram 50",
      colors: ["#4d2941", "#c46770", "#eaa487"],
      accent: "#eaa487",
      angle: 45,
      kind: "linear",
    },
    {
      id: "lumgram-24",
      name: "Peach Reverie",
      group: "LumGram 50",
      colors: ["#704957", "#d69b8d", "#eee0c1"],
      accent: "#eee0c1",
      angle: 180,
      kind: "linear",
    },
    {
      id: "lumgram-25",
      name: "Apricot Haze",
      group: "LumGram 50",
      colors: ["#6e4a34", "#c39064", "#e9cda0"],
      accent: "#e9cda0",
      angle: 110,
      kind: "linear",
    },
    {
      id: "lumgram-26",
      name: "Rose Noir",
      group: "LumGram 50",
      colors: ["#241b28", "#70374e", "#bf8593"],
      accent: "#bf8593",
      angle: 135,
      kind: "linear",
    },
    {
      id: "lumgram-27",
      name: "Sakura Rain",
      group: "LumGram 50",
      colors: ["#4b3b53", "#a687a5", "#dfc6ca"],
      accent: "#dfc6ca",
      angle: 160,
      kind: "linear",
    },
    {
      id: "lumgram-28",
      name: "Dusty Peony",
      group: "LumGram 50",
      colors: ["#4d2e42", "#b07d95", "#dbc1cd"],
      accent: "#dbc1cd",
      angle: 45,
      kind: "linear",
    },
    {
      id: "lumgram-29",
      name: "Velvet Berry",
      group: "LumGram 50",
      colors: ["#201529", "#73375f", "#cb7993"],
      accent: "#cb7993",
      angle: 180,
      kind: "radial",
    },
    {
      id: "lumgram-30",
      name: "Pink Opal",
      group: "LumGram 50",
      colors: ["#5e4d68", "#b59aad", "#e4d3d7"],
      accent: "#e4d3d7",
      angle: 110,
      kind: "linear",
    },
    {
      id: "lumgram-31",
      name: "Amethyst Studio",
      group: "LumGram 50",
      colors: ["#281e42", "#745785", "#b6a1cb"],
      accent: "#b6a1cb",
      angle: 135,
      kind: "linear",
    },
    {
      id: "lumgram-32",
      name: "Lilac Smoke",
      group: "LumGram 50",
      colors: ["#3e394e", "#8c83a4", "#c9c2d4"],
      accent: "#c9c2d4",
      angle: 160,
      kind: "linear",
    },
    {
      id: "lumgram-33",
      name: "Plum Obsidian",
      group: "LumGram 50",
      colors: ["#17101e", "#4c2756", "#966092"],
      accent: "#966092",
      angle: 45,
      kind: "linear",
    },
    {
      id: "lumgram-34",
      name: "Wisteria Night",
      group: "LumGram 50",
      colors: ["#181d36", "#5a537f", "#b097bd"],
      accent: "#b097bd",
      angle: 180,
      kind: "linear",
    },
    {
      id: "lumgram-35",
      name: "Orchid Bloom",
      group: "LumGram 50",
      colors: ["#352346", "#95659c", "#d4a8c8"],
      accent: "#d4a8c8",
      angle: 110,
      kind: "linear",
    },
    {
      id: "lumgram-36",
      name: "Cobalt Gallery",
      group: "LumGram 50",
      colors: ["#0d1d40", "#2d5990", "#90b2cf"],
      accent: "#90b2cf",
      angle: 135,
      kind: "radial",
    },
    {
      id: "lumgram-37",
      name: "Periwinkle Air",
      group: "LumGram 50",
      colors: ["#353f6b", "#8a96c2", "#c9cedc"],
      accent: "#c9cedc",
      angle: 160,
      kind: "linear",
    },
    {
      id: "lumgram-38",
      name: "Storm Atlas",
      group: "LumGram 50",
      colors: ["#1e2939", "#516276", "#9ca5ae"],
      accent: "#9ca5ae",
      angle: 45,
      kind: "linear",
    },
    {
      id: "lumgram-39",
      name: "Denim Dusk",
      group: "LumGram 50",
      colors: ["#202938", "#455b78", "#9ca9ba"],
      accent: "#9ca9ba",
      angle: 180,
      kind: "linear",
    },
    {
      id: "lumgram-40",
      name: "Azure Mirage",
      group: "LumGram 50",
      colors: ["#11313f", "#377a9c", "#b4c3b5"],
      accent: "#b4c3b5",
      angle: 110,
      kind: "linear",
    },
    {
      id: "lumgram-41",
      name: "Cyber Lotus",
      group: "LumGram 50",
      colors: ["#142638", "#7b326b", "#d78987"],
      accent: "#d78987",
      angle: 135,
      kind: "linear",
    },
    {
      id: "lumgram-42",
      name: "Prism Shift",
      group: "LumGram 50",
      colors: ["#264755", "#7062a0", "#c78191"],
      accent: "#c78191",
      angle: 160,
      kind: "linear",
    },
    {
      id: "lumgram-43",
      name: "Electric Iris",
      group: "LumGram 50",
      colors: ["#1e1639", "#634db4", "#af86c7"],
      accent: "#af86c7",
      angle: 45,
      kind: "radial",
    },
    {
      id: "lumgram-44",
      name: "Solar Flare",
      group: "LumGram 50",
      colors: ["#542337", "#ba5444", "#edaa58"],
      accent: "#edaa58",
      angle: 180,
      kind: "linear",
    },
    {
      id: "lumgram-45",
      name: "Neon Lagoon",
      group: "LumGram 50",
      colors: ["#10342e", "#1a8b81", "#ab64a1"],
      accent: "#ab64a1",
      angle: 110,
      kind: "linear",
    },
    {
      id: "lumgram-46",
      name: "Espresso Cloud",
      group: "LumGram 50",
      colors: ["#211c1a", "#675247", "#a59784"],
      accent: "#a59784",
      angle: 135,
      kind: "linear",
    },
    {
      id: "lumgram-47",
      name: "Cocoa Cashmere",
      group: "LumGram 50",
      colors: ["#32272b", "#7e6562", "#c9b6a1"],
      accent: "#c9b6a1",
      angle: 160,
      kind: "linear",
    },
    {
      id: "lumgram-48",
      name: "Oatmilk",
      group: "LumGram 50",
      colors: ["#6a6254", "#a99e88", "#e0d5c1"],
      accent: "#e0d5c1",
      angle: 45,
      kind: "linear",
    },
    {
      id: "lumgram-49",
      name: "Lunar Dust",
      group: "LumGram 50",
      colors: ["#282832", "#686672", "#a8a4ae"],
      accent: "#a8a4ae",
      angle: 180,
      kind: "linear",
    },
    {
      id: "lumgram-50",
      name: "Midnight Chrome",
      group: "LumGram 50",
      colors: ["#090c11", "#323e4a", "#889297"],
      accent: "#889297",
      angle: 110,
      kind: "radial",
    },
  ];
  const clamp = (v, min, max, fallback) =>
    Number.isFinite(Number(v))
      ? Math.max(min, Math.min(max, Number(v)))
      : fallback;
  const hex = (v, fallback = "#ffffff") =>
    /^#[0-9a-f]{6}$/i.test(v) ? v : fallback;
  function normalize(t = {}) {
    return {
      id: String(t.id || ""),
      name: String(t.name || "Untitled")
        .trim()
        .slice(0, 48),
      colors: [0, 1, 2].map((i) =>
        hex(t.colors?.[i], ["#252630", "#666773", "#cccccc"][i]),
      ),
      accent: hex(t.accent),
      angle: clamp(t.angle, 0, 360, 135),
      kind: t.kind === "radial" ? "radial" : "linear",
      group: t.group || "My presets",
      settings: t.settings && typeof t.settings === "object" ? t.settings : {},
      ...(t.css ? { css: t.css } : {}),
    };
  }
  function gradient(t) {
    if (builtins.includes(t) && t.portableGradient) return t.portableGradient;
    const v = normalize(t);
    return v.kind === "radial"
      ? `radial-gradient(ellipse at 25% 15%, ${v.colors[0]}, ${v.colors[1]} 50%, ${v.colors[2]})`
      : `linear-gradient(${v.angle}deg, ${v.colors[0]}, ${v.colors[1]} 50%, ${v.colors[2]})`;
  }
  const defaults = {
    lum_font_source: "native",
    lum_font_family: "inter",
    lum_font_device: "",
    lumgram_bg_mode: "theme",
    lumgram_bg_color: "#18181b",
    instagram_enable: "1",
    lumgram_animations: "1",
    instagram_theme_style: "ash",
    instagram_theme_id: "lumgram-01",
    instagram_icon_id: "icon",
    instagram_custom_bg: "",
    instagram_use_custom_bg: "0",
    instagram_bg_overlay_color: "#000000",
    instagram_bg_overlay_alpha: "-15",
    instagram_bg_image_blur: "0",
    instagram_bg_overlay_advanced: "0",
    instagram_bg_grad_tint: "20",
    instagram_bg_grad_lowest: "90",
    instagram_bg_grad_higher: "70",
    instagram_bg_grad_chat: "80",
    instagram_bg_grad_highest: "65",
    instagram_bg_grad_lower: "85",
    instagram_bg_grad_low: "80",
    instagram_bg_grad_high: "75",
    instagram_bg_grad_appframe: "70",
    lumgram_bg_opacity: 100,
    lumgram_bg_brightness: 100,
    lumgram_bg_contrast: 100,
    lumgram_bg_saturation: 100,
    lumgram_bg_x: 50,
    lumgram_bg_y: 50,
    lumgram_bg_zoom: 100,
    lumgram_bg_fit: "cover",
    lumgram_bg_base: "#161616",
    lumgram_bg_overlay: 55,
    lumgram_presets: [],
  };
  const backgroundKeys = Object.keys(defaults).filter(
    (k) =>
      /^(instagram_bg_|lumgram_bg_|lum_font_)/.test(k) ||
      ["instagram_custom_bg", "instagram_use_custom_bg"].includes(k),
  );
  function snapshot(state) {
    return Object.fromEntries(
      backgroundKeys.map((k) => [k, state[k] ?? defaults[k]]),
    );
  }
  function filter(settings) {
    return Object.fromEntries(
      backgroundKeys
        .filter((k) => Object.hasOwn(settings || {}, k))
        .map((k) => [k, settings[k]]),
    );
  }
  globalThis.LumGram = {
    builtins,
    normalize,
    gradient,
    clamp,
    hex,
    defaults,
    backgroundKeys,
    snapshot,
    filter,
  };
})();
